---
- name: print vars
  debug:
    var: "{{ mysql_readonly_users }}"

- name: Add read only users to the DB
  mysql_user:
    name: "{{ item.key }}"
    state: present
    password: "{{ item.value.password }}"
    priv: '*.*:SELECT'
  with_dict: "{{ mysql_readonly_users }}"
