---
- name: Add read only users to the DB
  mysql_user:
    name: "{{ item.value.usernames }}"
    state: present
    password: "{{ item['defaultPassword'] }}"
    priv: '*.*:SELECT'
  with_dict: "{{ mysql_readonly_users }}"
